package fr.polytechnice.caddyhop.activities;

import android.content.ActivityNotFoundException;
import android.content.Intent;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;
import android.widget.ImageView;

import com.google.android.gms.vision.barcode.Barcode;

import net.glxn.qrgen.android.QRCode;

import fr.polytechnice.caddyhop.R;

/**
 * Created by shafiq on 10/06/16.
 *
 * A simple activity that show a QR code generated by a certain data.
 *
 * TODO: QR code should be generated depending on the items scanned
 */

public class ShowQRCodeActivity extends AppCompatActivity {

    // TODO: use ButterKnife
    ImageView imageView;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.qrcode_view);
        String data = getIntent().getStringExtra("qrcodedata");

        imageView = (ImageView) findViewById(R.id.generated_qrcode);

        Bitmap bitmap = QRCode.from(data).withSize(600,600).bitmap();

        imageView.setImageBitmap(bitmap);
    }
}
